/*!
@file		GlobalDefine.h
@author     Leong Jun Xiang (junxiang.leong)
@course		CSD1400
@brief		contains all the variables for rendering
			contains all character types
			Copyright © 2020 DigiPen, All rights reserved.
*//*_________________________________________________________________________*/
#ifndef GLOBALDEFINE_H
#define GLOBALDEFINE_H
#include "Misc/VariableList.h"

typedef enum IMAGE_TYPE
{
	IMAGE_APPLE = 0,
	IMAGE_CIRCLE,
	IMAGE_PLAYER,
	IMAGE_TILE1,
	IMAGE_TILE2,
	IMAGE_SLIME,
	IMAGE_TRIANGLE,
	IMAGE_TURRET,
	IMAGE_BULLET,
	IMAGE_SMOKE,
	IMAGE_INFO,
	IMAGE_SPIKE,
	IMAGE_DIALOGUE,
	IMAGE_TESTSPRITE,
	IMAGE_PLAYERDASH,
	IMAGE_ALERT,
	IMAGE_CIRCLEPARTICLE,
	IMAGE_TRIANGLEPARTICLE,
	IMAGE_PLAYERPARTICLE,
	IMAGE_HEART,
	IMAGE_PLAYERSPRITESHEET,
	IMAGE_SLIMESPRITESHEET,
	IMAGE_TILE_START,
	IMAGE_TILE_END,
	IMAGE_PARA_BACK_MOUNT, //PARA
	IMAGE_PARA_BACK_TREES,
	IMAGE_PARA_CLOUDS,
	IMAGE_PARA_FRONT_MOUNT,
	IMAGE_PARA_FRONT_TREES,
	IMAGE_PARA_MIST, 
	IMAGE_PARA_BACK_ROCKS,
	IMAGE_PARA_FRONT_ROCKS,//PARA_END
	IMAGE_MAPEDITOR_CURSOR,
	IMAGE_SLIMEPARTICLES,
	IMAGE_LEGEND,
	IMAGE_SPEECH_BUBBLE,
	IMAGE_CHICK,
	IMAGE_FOX,
	IMAGE_PIG,
	MAX_IMAGE
} IMAGE_TYPE;

typedef enum CharacterTag
{
	CHARACTER_PLAYER,
	CHARACTER_ENEMY_CIRCLE,
	CHARACTER_ENEMY_TRIANGLE,
	CHARACTER_ENEMY_TURRET,
	CHARACTER_ENEMY_SPIKES,
	CHARACTER_EMEMY_BOUNCE,
	CHARACTER_HEART,
}CharacterTag;

typedef enum STAGE
{
	STAGE_TUTORIAL = 0,
	STAGE_1,
	STAGE_2,
	STAGE_3,
	STAGE_4,
	MAX_STAGE
} STAGE;

static VariableList g_imageList;

STAGE currentStage;

VariableList g_characterList;
#endif // !GLOBALDEFINE_H
